---
deployment:
  tasks:
    # 1. Ruta de destino (Corregida según tus logs anteriores)
    # Tus logs mostraron: /home/grupaqgl/sga.90s.agency
    # NO uses public_html si tu subdominio está en la raíz de tu usuario.
    - export DEPLOYPATH=/home/grupaqgl/sga.90s.agency/

    # 2. Copiar archivos nuevos/modificados
    # -R = Recursivo, -u = Update (solo copia si es más nuevo)
    - /bin/cp -R * $DEPLOYPATH
    
    # 3. Copiar explícitamente el archivo de entorno y la configuración
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    
    # 4. (Opcional) Permisos - Asegura que las carpetas sean escribibles
    # Esto evita errores 500 o de "permiso denegado" en logs
    # - /bin/chmod -R 755 $DEPLOYPATH/public
    # - /bin/chmod -R 775 $DEPLOYPATH/storage