---
deployment:
  tasks:
    # 1. Definir la ruta de destino (La carpeta pública de tu dominio)
    # IMPORTANTE: Cambia 'tu_usuario' por tu usuario real de cPanel
    # Si es el dominio principal, suele ser /home/tu_usuario/public_html
    # Si es un subdominio, suele ser /home/tu_usuario/public_html/subdominio
    - export DEPLOYPATH=/home/grupaqgl/public_html/sga

    # 2. Copiar los archivos del repositorio a la carpeta pública
    # La bandera -R es recursiva (carpetas)
    # Excluimos la carpeta .git para seguridad
    - /bin/cp -R * $DEPLOYPATH
    
    # 3. Copiar archivos ocultos importantes (como .env.example o .gitignore si se necesitan)
    # Nota: No copiamos .git
    - /bin/cp .env.example $DEPLOYPATH
    
    # Opcional: Si quieres que intente ejecutar comandos de composer automáticamente
    # (A veces falla por permisos en servidores compartidos, mejor hacerlo m anual la primera vez)
    # - /bin/cd $DEPLOYPATH && /usr/bin/composer install --no-dev