---
deployment:
  tasks:
    # Define la carpeta de despliegue
    - export DEPLOYDIR=/home/grupaqgl/sga-centu

    # 1. Instala las dependencias de PHP (el "motor" de Laravel)
    # Usamos la ruta completa a composer de cPanel para más seguridad
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader -d $DEPLOYDIR
    
    # 2. Limpia y guarda la caché de configuración
    - php $DEPLOYDIR/artisan config:cache
    
    # 3. Limpia y guarda la caché de rutas
    - php $DEPLOYDIR/artisan route:cache
    
    # 4. Limpia la caché de vistas (importante para Blade/Livewire)
    - php $DEPLOYDIR/artisan view:clear